/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List keys */
        get: operations["listKeys"];
        put?: never;
        /** Create key */
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview keyring import
         * @description Parse armored key material without persisting. Returns primary and subkey metadata,
         *     revocation state read from the keyring, and warnings when public/private blocks differ.
         */
        post: operations["previewKeyring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get key */
        get: operations["getKey"];
        put?: never;
        post?: never;
        /** Delete key */
        delete: operations["deleteKey"];
        options?: never;
        head?: never;
        /** Update key */
        patch: operations["updateKey"];
        trace?: never;
    };
    "/api/keys/{primaryKeyId}/subkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subkeys */
        get: operations["listSubkeys"];
        put?: never;
        /** Create subkey */
        post: operations["createSubkey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{primaryKeyId}/subkeys/import-from-keyring/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview import subkeys from stored keyring
         * @description Parse the primary's stored armored keyring and show which subkey rows would be
         *     registered, updated (revocation sync), or skipped without writing to the database.
         *     Primary revocation state is not part of this preview — only subkey rows are considered.
         */
        post: operations["previewImportSubkeysFromKeyring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{primaryKeyId}/subkeys/import-from-keyring": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import subkey rows from stored keyring
         * @description Parses non-master keys from the primary's stored armored keyring and registers metadata-only
         *     subkey rows for any fingerprints not already registered under this primary. Idempotent —
         *     existing subkey rows that are already up to date are skipped. Active subkey rows whose
         *     fingerprints are revoked in the stored keyring are synced to revoked (`updated` /
         *     `updatedCount`). Primary revocation is detected on initial register only; this endpoint
         *     does not update the primary row. Returns `201` when new rows are registered, `200` when
         *     `registered` is empty (all skipped/synced or no subkeys in the keyring).
         */
        post: operations["importSubkeysFromKeyring"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{primaryKeyId}/subkeys/{subkeyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subkey */
        get: operations["getSubkey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke key
         * @description Revokes a primary or subkey. When the account's primary key row stores encrypted private
         *     material, `passphrase` is required and the OpenPGP keyring is updated cryptographically.
         *     Without stored private material, only database metadata (`revokedAt`, `revocationReason`) is
         *     updated. Supplying a passphrase when no private material exists returns 400.
         */
        post: operations["revokeKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/extend-expiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extend key expiry */
        post: operations["extendKeyExpiry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate subkey
         * @description Creates a replacement subkey on the parent primary. `passphrase` is required (unlocks the
         *     primary keyring for new subkey creation; rotate is only supported when the primary stores
         *     private material). When `revokePrevious` is true (default), the previous subkey is also
         *     revoked in the OpenPGP keyring; when false, the previous subkey row is left unchanged in
         *     the keyring.
         */
        post: operations["rotateKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/export-public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export public key */
        get: operations["exportPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/export-ssh-public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export OpenSSH public key
         * @description Returns a one-line OpenSSH public key for keys with the `authenticate` capability
         *     and an SSH-compatible algorithm (`ed25519`, `rsa`, or `ecdsa`). Encryption-only
         *     algorithms (for example `cv25519`) and keys without `authenticate` return 400.
         */
        get: operations["exportSshPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (Spring `ProblemDetail` JSON) */
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Field validation errors (400 responses) */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        HelloResponse: {
            message: string;
        };
        /** @enum {string} */
        KeyRole: "primary" | "subkey";
        /** @enum {string} */
        KeyStatus: "active" | "expired" | "revoked";
        /** @enum {string} */
        PgpCapability: "certify" | "sign" | "encrypt" | "authenticate";
        /** @enum {string} */
        MaterialKind: "public" | "private";
        AlgorithmSpec: {
            /**
             * @description ed448 and x448 require openpgpVersion 6 when generating keys.
             * @enum {string}
             */
            algorithm: "rsa" | "ed25519" | "cv25519" | "ecdsa" | "ecdh" | "ed448" | "x448";
            /** @enum {integer} */
            keySize?: 2048 | 3072 | 4096;
            /** @description Required for ecdh; required for ecdsa signing subkeys. Examples P-256, P-384, nistp256. */
            curve?: string;
        };
        ValiditySpec: {
            /** Format: date-time */
            expiresAt: string;
        };
        UserIdSpec: {
            name: string;
            /** Format: email */
            email?: string;
        };
        /**
         * @description Dual-purpose body for `POST /api/keys`.
         *
         *     **Generate path:** include `algorithmSpec`, `passphrase`, and optional `userIds` / `validity`.
         *     **Register/import path:** include `armoredPublic` and/or `encryptedPrivateArmored`; the server parses
         *     metadata (fingerprint, key ID, algorithm, capabilities, expiry) from the armored material.
         *     When the armored keyring contains subkeys, metadata-only subkey rows are registered automatically
         *     under the new primary (same storage model as create-subkey — armored material stays on the primary row).
         *     `fingerprint` is optional on register — when omitted the server derives it; when provided it must match.
         *     When both armored blocks are sent they must refer to the same key or the request is rejected.
         *     Client-supplied `capabilities`, `algorithm`, `keyId`, and `expiresAt` are ignored on register;
         *     parsed values from the armored material are always stored.
         */
        CreatePgpKeyRequest: {
            label?: string;
            /**
             * @description Optional on register/import. When omitted, derived from armored key material.
             *     When provided, must match the parsed fingerprint or the request is rejected.
             */
            fingerprint?: string;
            keyType?: components["schemas"]["MaterialKind"];
            algorithmSpec?: components["schemas"]["AlgorithmSpec"];
            capabilities?: components["schemas"]["PgpCapability"][];
            validity?: components["schemas"]["ValiditySpec"];
            userIds?: components["schemas"]["UserIdSpec"][];
            passphrase?: string;
            /**
             * @description OpenPGP key packet version for generated primary keys (RFC 4880 v4 or RFC 9580 v6).
             *     Omitted defaults to 4. Subkeys inherit the primary key version.
             * @default 4
             * @enum {integer}
             */
            openpgpVersion: 4 | 6;
            /** @description Required for register/import unless `encryptedPrivateArmored` is provided. */
            armoredPublic?: string;
            /** @description Required for private register/import when `armoredPublic` is omitted. */
            encryptedPrivateArmored?: string;
        };
        CreateSubkeyRequest: {
            capabilities: components["schemas"]["PgpCapability"][];
            algorithm: components["schemas"]["AlgorithmSpec"];
            validity?: components["schemas"]["ValiditySpec"];
            passphrase?: string;
        };
        UpdatePgpKeyRequest: {
            label?: string;
            /** Format: date-time */
            expiresAt?: string;
            storageProvider?: string;
            storageRef?: string;
        };
        RevokeKeyRequest: {
            /** @enum {string} */
            reason: "no_reason" | "key_superseded" | "key_compromised" | "key_retired" | "user_id_invalid";
            description?: string;
            passphrase?: string;
        };
        ExtendExpiryRequest: {
            /** Format: date-time */
            expiresAt: string;
            passphrase?: string;
        };
        RotateKeyRequest: {
            capabilities: components["schemas"]["PgpCapability"][];
            algorithm: components["schemas"]["AlgorithmSpec"];
            validity?: components["schemas"]["ValiditySpec"];
            /**
             * @description Required for rotate. Unlocks the primary keyring for new subkey creation (and for
             *     revoking the previous subkey when `revokePrevious` is true).
             */
            passphrase?: string;
            /**
             * @description When true (default), revokes the previous subkey in the OpenPGP keyring before creating
             *     the replacement. Does not affect whether `passphrase` is required.
             */
            revokePrevious?: boolean;
        };
        RotateKeyResponse: {
            newKey: components["schemas"]["PgpKey"];
            previousKey: components["schemas"]["PgpKey"];
        };
        ImportSubkeysResponse: {
            /** @description Newly registered subkey rows from this import. */
            registered: components["schemas"]["PgpKeySummary"][];
            /** @description Subkeys already registered under this primary that were skipped. */
            skippedCount: number;
            /** @description Existing subkey rows synced to revoked status from the keyring. */
            updated: components["schemas"]["PgpKeySummary"][];
            /** @description Number of existing subkey rows updated (revocation sync). */
            updatedCount: number;
        };
        PreviewKeyEntry: {
            role: components["schemas"]["KeyRole"];
            fingerprint: string;
            keyId: string;
            algorithm: string;
            capabilities: components["schemas"]["PgpCapability"][];
            /** Format: date-time */
            expiresAt?: string | null;
            status: components["schemas"]["KeyStatus"];
            /** Format: date-time */
            revokedAt?: string | null;
            revocationReason?: string | null;
            /** @enum {integer} */
            openpgpVersion: 4 | 6;
        };
        PreviewKeyringResponse: {
            primary: components["schemas"]["PreviewKeyEntry"];
            subkeys: components["schemas"]["PreviewKeyEntry"][];
            warnings: string[];
            /**
             * @description Which armored block(s) were used; when both are pasted, private is authoritative.
             * @enum {string}
             */
            source: "public" | "private" | "both";
        };
        PreviewImportSubkeysResponse: {
            wouldRegister: components["schemas"]["PreviewKeyEntry"][];
            wouldUpdate: components["schemas"]["PreviewKeyEntry"][];
            wouldSkipCount: number;
            warnings: string[];
            /** @enum {string} */
            source: "public" | "private" | "both";
        };
        PgpKeySummary: {
            /** Format: uuid */
            id?: string;
            /** @description User-facing key name. `null` when unset. */
            label?: string | null;
            fingerprint?: string;
            /** @description OpenPGP key ID (16 uppercase hex characters). */
            keyId?: string;
            /**
             * @description Stored algorithm identifier (e.g. `ed25519`, `cv25519`). Parsed from armored material on
             *     register or set on generation.
             */
            algorithm?: string;
            keyType?: components["schemas"]["MaterialKind"];
            role?: components["schemas"]["KeyRole"];
            /** Format: uuid */
            parentKeyId?: string | null;
            /** @description Always present in responses; empty array when no capabilities are stored. */
            capabilities?: components["schemas"]["PgpCapability"][];
            status?: components["schemas"]["KeyStatus"];
            /**
             * Format: date-time
             * @description Key expiration instant. `null` means the key does not expire (no OpenPGP key-expiration subpacket).
             */
            expiresAt?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
            /**
             * @description OpenPGP packet version for this keyring (primary sets it; subkeys inherit).
             * @enum {integer}
             */
            openpgpVersion?: 4 | 6;
        };
        PgpKey: components["schemas"]["PgpKeySummary"] & {
            /** @description Present on primary keys; omitted on subkey list/detail responses. */
            armoredPublic?: string;
            /** @description Present on primary detail when generated or imported with private material. */
            encryptedPrivateArmored?: string;
            /**
             * @description Present on primary register responses when subkey rows were auto-imported from a
             *     multi-key armored export. Omitted on generate and on other responses.
             */
            registeredSubkeyCount?: number;
        };
    };
    responses: {
        /** @description RFC 7807 problem details (typical 400, 401, 404, or 409) */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        KeyId: string;
        PrimaryKeyId: string;
        SubkeyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloResponse"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    listKeys: {
        parameters: {
            query?: {
                role?: components["schemas"]["KeyRole"];
                status?: components["schemas"]["KeyStatus"];
                capability?: components["schemas"]["PgpCapability"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKeySummary"][];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePgpKeyRequest"];
            };
        };
        responses: {
            /** @description Primary key created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    previewKeyring: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePgpKeyRequest"];
            };
        };
        responses: {
            /** @description Parsed keyring preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewKeyringResponse"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    getKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    deleteKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    updateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePgpKeyRequest"];
            };
        };
        responses: {
            /** @description Updated key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    listSubkeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                primaryKeyId: components["parameters"]["PrimaryKeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subkey list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKeySummary"][];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    createSubkey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                primaryKeyId: components["parameters"]["PrimaryKeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSubkeyRequest"];
            };
        };
        responses: {
            /** @description Subkey created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    previewImportSubkeysFromKeyring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                primaryKeyId: components["parameters"]["PrimaryKeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Import preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewImportSubkeysResponse"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    importSubkeysFromKeyring: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                primaryKeyId: components["parameters"]["PrimaryKeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Idempotent sync completed with no new subkey rows (`registered` is empty). All keyring
             *     subkeys were already registered, or the keyring has no subkeys.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSubkeysResponse"];
                };
            };
            /** @description One or more new subkey rows were registered from the keyring. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportSubkeysResponse"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    getSubkey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                primaryKeyId: components["parameters"]["PrimaryKeyId"];
                subkeyId: components["parameters"]["SubkeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subkey details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RevokeKeyRequest"];
            };
        };
        responses: {
            /** @description Revoked key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    extendKeyExpiry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExtendExpiryRequest"];
            };
        };
        responses: {
            /** @description Key with updated expiry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    rotateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RotateKeyRequest"];
            };
        };
        responses: {
            /** @description Rotation result with new and previous subkeys */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateKeyResponse"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    exportPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Armored public key material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pgp-keys": string;
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    exportSshPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenSSH authorized_keys line (type, base64, comment) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
}
