/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hello */
        get: operations["getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List keys */
        get: operations["listKeys"];
        put?: never;
        /** Create key */
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get key */
        get: operations["getKey"];
        put?: never;
        post?: never;
        /** Delete key */
        delete: operations["deleteKey"];
        options?: never;
        head?: never;
        /** Update key */
        patch: operations["updateKey"];
        trace?: never;
    };
    "/api/keys/{primaryKeyId}/subkeys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List subkeys */
        get: operations["listSubkeys"];
        put?: never;
        /** Create subkey */
        post: operations["createSubkey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{primaryKeyId}/subkeys/{subkeyId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subkey */
        get: operations["getSubkey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke key
         * @description Revokes a primary or subkey. When the account's primary key row stores encrypted private
         *     material, `passphrase` is required and the OpenPGP keyring is updated cryptographically.
         *     Without stored private material, only database metadata (`revokedAt`, `revocationReason`) is
         *     updated. Supplying a passphrase when no private material exists returns 400.
         */
        post: operations["revokeKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/extend-expiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Extend key expiry */
        post: operations["extendKeyExpiry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/rotate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate subkey
         * @description Creates a replacement subkey on the parent primary. When `revokePrevious` is true (default),
         *     the previous subkey is revoked in the OpenPGP keyring and `passphrase` is required.
         */
        post: operations["rotateKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/{keyId}/export-public": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export public key */
        get: operations["exportPublicKey"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (Spring `ProblemDetail` JSON) */
        ProblemDetail: {
            /** Format: uri */
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
            /** Format: uri */
            instance?: string;
            /** @description Field validation errors (400 responses) */
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        HelloResponse: {
            message: string;
        };
        /** @enum {string} */
        KeyRole: "primary" | "subkey";
        /** @enum {string} */
        KeyStatus: "active" | "expired" | "revoked";
        /** @enum {string} */
        PgpCapability: "certify" | "sign" | "encrypt" | "authenticate";
        /** @enum {string} */
        MaterialKind: "public" | "private";
        AlgorithmSpec: {
            /** @enum {string} */
            algorithm: "rsa" | "ed25519" | "cv25519" | "ecdsa" | "ecdh";
            /** @enum {integer} */
            keySize?: 2048 | 3072 | 4096;
            /** @description Required for ecdh; required for ecdsa signing subkeys. Examples P-256, P-384, nistp256. */
            curve?: string;
        };
        ValiditySpec: {
            /** Format: date-time */
            expiresAt: string;
        };
        UserIdSpec: {
            name: string;
            /** Format: email */
            email?: string;
        };
        CreatePgpKeyRequest: {
            label?: string;
            fingerprint?: string;
            keyType?: components["schemas"]["MaterialKind"];
            algorithmSpec?: components["schemas"]["AlgorithmSpec"];
            capabilities?: components["schemas"]["PgpCapability"][];
            validity?: components["schemas"]["ValiditySpec"];
            userIds?: components["schemas"]["UserIdSpec"][];
            passphrase?: string;
            /**
             * @description OpenPGP key packet version for generated primary keys (RFC 4880 v4 or RFC 9580 v6).
             *     Omitted defaults to 4. Subkeys inherit the primary key version.
             * @default 4
             * @enum {integer}
             */
            openpgpVersion: 4 | 6;
            armoredPublic?: string;
            encryptedPrivateArmored?: string;
        };
        CreateSubkeyRequest: {
            capabilities: components["schemas"]["PgpCapability"][];
            algorithm: components["schemas"]["AlgorithmSpec"];
            validity?: components["schemas"]["ValiditySpec"];
            passphrase?: string;
        };
        UpdatePgpKeyRequest: {
            label?: string;
            /** Format: date-time */
            expiresAt?: string;
            storageProvider?: string;
            storageRef?: string;
        };
        RevokeKeyRequest: {
            /** @enum {string} */
            reason: "no_reason" | "key_superseded" | "key_compromised" | "key_retired" | "user_id_invalid";
            description?: string;
            passphrase?: string;
        };
        ExtendExpiryRequest: {
            /** Format: date-time */
            expiresAt: string;
            passphrase?: string;
        };
        RotateKeyRequest: {
            capabilities: components["schemas"]["PgpCapability"][];
            algorithm: components["schemas"]["AlgorithmSpec"];
            validity?: components["schemas"]["ValiditySpec"];
            passphrase?: string;
            /** @description When true, requires passphrase to revoke the previous subkey in the keyring. */
            revokePrevious?: boolean;
        };
        RotateKeyResponse: {
            newKey: components["schemas"]["PgpKey"];
            previousKey: components["schemas"]["PgpKey"];
        };
        PgpKeySummary: {
            /** Format: uuid */
            id?: string;
            fingerprint?: string;
            keyType?: components["schemas"]["MaterialKind"];
            role?: components["schemas"]["KeyRole"];
            /** Format: uuid */
            parentKeyId?: string | null;
            capabilities?: components["schemas"]["PgpCapability"][];
            status?: components["schemas"]["KeyStatus"];
            /** Format: date-time */
            expiresAt?: string | null;
            /** Format: date-time */
            revokedAt?: string | null;
            /**
             * @description OpenPGP packet version for this keyring (primary sets it; subkeys inherit).
             * @enum {integer}
             */
            openpgpVersion?: 4 | 6;
        };
        PgpKey: components["schemas"]["PgpKeySummary"] & {
            /** @description Present on primary keys; omitted on subkey list/detail responses. */
            armoredPublic?: string;
            /** @description Present on primary detail when generated or imported with private material. */
            encryptedPrivateArmored?: string;
        };
    };
    responses: {
        /** @description RFC 7807 problem details (typical 400, 401, 404, or 409) */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetail"];
            };
        };
    };
    parameters: {
        KeyId: string;
        PrimaryKeyId: string;
        SubkeyId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HelloResponse"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    listKeys: {
        parameters: {
            query?: {
                role?: components["schemas"]["KeyRole"];
                status?: components["schemas"]["KeyStatus"];
                capability?: components["schemas"]["PgpCapability"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKeySummary"][];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePgpKeyRequest"];
            };
        };
        responses: {
            /** @description Primary key created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    getKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    deleteKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    updateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdatePgpKeyRequest"];
            };
        };
        responses: {
            /** @description Updated key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    listSubkeys: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                primaryKeyId: components["parameters"]["PrimaryKeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subkey list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKeySummary"][];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    createSubkey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                primaryKeyId: components["parameters"]["PrimaryKeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CreateSubkeyRequest"];
            };
        };
        responses: {
            /** @description Subkey created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    getSubkey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                primaryKeyId: components["parameters"]["PrimaryKeyId"];
                subkeyId: components["parameters"]["SubkeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subkey details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    revokeKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RevokeKeyRequest"];
            };
        };
        responses: {
            /** @description Revoked key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    extendKeyExpiry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ExtendExpiryRequest"];
            };
        };
        responses: {
            /** @description Key with updated expiry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PgpKey"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    rotateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RotateKeyRequest"];
            };
        };
        responses: {
            /** @description Rotation result with new and previous subkeys */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RotateKeyResponse"];
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
    exportPublicKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                keyId: components["parameters"]["KeyId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Armored public key material */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pgp-keys": string;
                };
            };
            "4XX": components["responses"]["ErrorResponse"];
        };
    };
}
