spring:
  datasource:
    url: jdbc:h2:mem:pgpkeymanager-${random.uuid};MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-test.sql

app:
  auth0:
    issuer-uri:
    audience:
  storage:
    aws:
      enabled: false
